CREATE TABLE ARTISTA (
    ID_ARTISTA SERIAL PRIMARY KEY,
    NOME_ARTISTA VARCHAR(255) NOT NULL
);

CREATE TABLE ALBUM (
    ID_ALBUM SERIAL PRIMARY KEY,
    TITULO_ALBUM VARCHAR(255) NOT NULL
);

CREATE TABLE ARTISTA_ALBUM (
    ID_ARTISTA INTEGER NOT NULL,
    ID_ALBUM INTEGER NOT NULL,      
    PRIMARY KEY (ID_ARTISTA, ID_ALBUM),    
    CONSTRAINT FK_ARTISTA FOREIGN KEY (ID_ARTISTA) REFERENCES ARTISTA(ID_ARTISTA) ON DELETE CASCADE,
    CONSTRAINT FK_ALBUM FOREIGN KEY (ID_ALBUM) REFERENCES ALBUM(ID_ALBUM) ON DELETE CASCADE
);