
INSERT INTO ARTISTA (ID_ARTISTA, NOME_ARTISTA) VALUES 
(1, 'SERJ TANKIAN'), (2, 'MIKE SHINODA'), (3, 'MICHEL TELÓ'),(4, 'GUNS N’ ROSES');


INSERT INTO ALBUM (ID_ALBUM, TITULO_ALBUM) VALUES 
(1, 'HARAKIRI'), (2, 'BLACK BLOOMS'), (3, 'THE ROUGH DOG'), 
(4, 'THE RISING TIED'), (5, 'POST TRAUMATIC'), (6, 'POST TRAUMATIC EP'), (7, 'WHERE’D YOU GO'), 
(8, 'BEM SERTANEJO'), (9, 'BEM SERTANEJO - O SHOW (AO VIVO)'), (10, 'BEM SERTANEJO - (1ª TEMPORADA) - EP'),
(11, 'USE YOUR ILLUSION I'), (12, 'USE YOUR ILLUSION II'), (13, 'GREATEST HITS');


INSERT INTO ARTISTA_ALBUM (ID_ARTISTA, ID_ALBUM) VALUES 
(1, 1), (1, 2), (1, 3), (2, 4), (2, 5), (2, 6), (2, 7), 
(3, 8), (3, 9), (3, 10), (4, 11), (4, 12), (4, 13);


SELECT SETVAL('ARTISTA_ID_ARTISTA_SEQ', (SELECT MAX(ID_ARTISTA) FROM ARTISTA));
SELECT SETVAL('ALBUM_ID_ALBUM_SEQ', (SELECT MAX(ID_ALBUM) FROM ALBUM));