CREATE TABLE USUARIO (
    ID_USUARIO SERIAL PRIMARY KEY,
    LOGIN_USUARIO VARCHAR(255) NOT NULL,
    PASSWORD_USUARIO VARCHAR(2048),
    KEY_USUARIO VARCHAR(500)
);

CREATE INDEX IDX_USUARIO_LOGIN ON USUARIO(LOGIN_USUARIO);


CREATE TABLE TOKENS (
    ID_TOKENS BIGSERIAL PRIMARY KEY,
    ID_USUARIO BIGINT NOT NULL,
    NOME_TOKEN VARCHAR(500) NOT NULL UNIQUE,
    THEN_TOKEN TIMESTAMP NOT NULL        
);