CREATE TABLE ALBUM_CAPA (
    ID_CAPA SERIAL PRIMARY KEY,
    ID_ALBUM INTEGER NOT NULL,
    NOME_ARQUIVO VARCHAR(255) NOT NULL,
    OBJETO_MINIO VARCHAR(512) NOT NULL UNIQUE,
    CONSTRAINT FK_ALBUM_CAPA_ALBUM FOREIGN KEY (ID_ALBUM) REFERENCES ALBUM(ID_ALBUM) ON DELETE CASCADE
);

